In [22]:
import glob

import pandas as pd

UNCERTAINTY_TYPE = 'ALL'
METRICS = [  'PRR (MAE)']

path = "./results-ENS (LGBM)-ERROR/*.csv"

df_raw = pd.DataFrame()

for fname in glob.glob(path):

    if fname.endswith("-rejection-curve.csv") or fname.endswith("-pred-probas.csv") or fname.endswith(
            "-true-classes.csv"):
        continue

    print(fname)
    
    df = pd.read_csv(fname)

    df_raw = pd.concat([df_raw, df])

df_raw

print(df_raw[df_raw.isna().any(axis=1)])
df_raw = df_raw.fillna(0)

if not UNCERTAINTY_TYPE == 'ALL':
    df_raw = df_raw[df_raw['Uncertainty Type'] == UNCERTAINTY_TYPE]

df_raw = df_raw.sort_values(['Uncertainty Measure', 'Dataset'])

./results-ENS (LGBM)-ERROR\Abalone.csv
./results-ENS (LGBM)-ERROR\Auto MPG.csv
./results-ENS (LGBM)-ERROR\Automobile.csv
./results-ENS (LGBM)-ERROR\Balance Scale.csv
./results-ENS (LGBM)-ERROR\Boston Housing.csv
./results-ENS (LGBM)-ERROR\CMC.csv
./results-ENS (LGBM)-ERROR\ERA.csv
./results-ENS (LGBM)-ERROR\ESL.csv
./results-ENS (LGBM)-ERROR\Eucalyptus.csv
./results-ENS (LGBM)-ERROR\Grub Damage.csv
./results-ENS (LGBM)-ERROR\Heart (CLE).csv
./results-ENS (LGBM)-ERROR\LEV.csv
./results-ENS (LGBM)-ERROR\Machine CPU.csv
./results-ENS (LGBM)-ERROR\New Thyroid.csv
./results-ENS (LGBM)-ERROR\Obesity.csv
./results-ENS (LGBM)-ERROR\Wisconsin Breast Cancer.csv
              Uncertainty Measure Uncertainty Type      Dataset  PRR (MCR)  \
36                        Entropy               TU  New Thyroid        NaN
37                        Entropy               EU  New Thyroid        NaN
38                        Entropy               AU  New Thyroid        NaN
39                Binary Variance               TU  New Thyroid        NaN
40                Binary Variance               EU  New Thyroid        NaN
..                            ...              ...          ...        ...
175  Binary Variance One vs. Rest               EU  New Thyroid        NaN
176  Binary Variance One vs. Rest               AU  New Thyroid        NaN
177   Binary Entropy One vs. Rest               TU  New Thyroid        NaN
178   Binary Entropy One vs. Rest               EU  New Thyroid        NaN
179   Binary Entropy One vs. Rest               AU  New Thyroid        NaN

     PRR (MAE)  PRR (MSE)
36         NaN        NaN
37         NaN        NaN
38         NaN        NaN
39         NaN        NaN
40         NaN        NaN
..         ...        ...
175        NaN        NaN
176        NaN        NaN
177        NaN        NaN
178        NaN        NaN
179        NaN        NaN

[72 rows x 6 columns]

In [23]:
if not UNCERTAINTY_TYPE == 'ALL':
    # Rename uncertainty measures
    df_raw = df_raw.replace(f'Entropy', f"$\\text{{{UNCERTAINTY_TYPE}}}_{{\\,\\text{{ent}}}}$")
    df_raw = df_raw.replace(f'Variance', f"$\\text{{{UNCERTAINTY_TYPE}}}_{{\\,\\text{{var}}}}$")
    df_raw = df_raw.replace(f"Binary Entropy", f"$\\text{{{UNCERTAINTY_TYPE}}}_{{\\,\\text{{ord-ent}}}}$")
    df_raw = df_raw.replace(f"Binary Variance", f"$\\text{{{UNCERTAINTY_TYPE}}}_{{\\,\\text{{ord-var}}}}$")
    df_raw = df_raw.replace(f"Binary Entropy One vs. Rest", f"$\\text{{{UNCERTAINTY_TYPE}}}_{{\\,\\text{{bin-ent}}}}$")
    df_raw = df_raw.replace(f"Binary Variance One vs. Rest", f"$\\text{{{UNCERTAINTY_TYPE}}}_{{\\,\\text{{bin-var}}}}$")
else:
    # Rename uncertainty measures
    df_raw = df_raw.replace("Entropy", "ent")
    df_raw = df_raw.replace("Variance", "var")
    df_raw = df_raw.replace("Binary Entropy", "ord-ent")
    df_raw = df_raw.replace("Binary Variance", "ord-var")
    df_raw = df_raw.replace(f"Binary Entropy One vs. Rest", "bin-ent")
    df_raw = df_raw.replace(f"Binary Variance One vs. Rest", "bin-var")


# Rename uncertainty measures
# df_raw = df_raw.replace("Entropy", "ent")
# df_raw = df_raw.replace("Variance", "var")
# df_raw = df_raw.replace("Binary Entropy", "ord-ent")
# df_raw = df_raw.replace("Binary Variance", "ord-var")

In [24]:
df_raw.index.name = 'index'
df_raw['index'] = df_raw.index
df_raw

,Uncertainty Measure,Uncertainty Type,Dataset,PRR (MCR),PRR (MAE),PRR (MSE),index
index,,,,,,,
6,ord-ent,TU,Abalone,0.196734,0.288851,0.319262,6
7,ord-ent,EU,Abalone,0.170817,0.242937,0.267086,7
8,ord-ent,AU,Abalone,0.199899,0.290685,0.318964,8
24,ord-ent,TU,Abalone,0.209714,0.304864,0.442227,24
25,ord-ent,EU,Abalone,0.211950,0.309945,0.453589,25
...,...,...,...,...,...,...,...
154,var,EU,Wisconsin Breast Cancer,-0.313830,0.050868,0.019804,154
155,var,AU,Wisconsin Breast Cancer,-0.169453,-0.088029,-0.024463,155
171,var,TU,Wisconsin Breast Cancer,0.177052,0.489815,0.612026,171
172,var,EU,Wisconsin Breast Cancer,-0.313830,-0.208025,-0.155894,172
173,var,AU,Wisconsin Breast Cancer,0.177052,0.489815,0.612026,173

In [25]:
i = 0
j = 0
while True:
    if j == len(df_raw):
        break
    df_raw.iloc[j, df_raw.columns.get_loc('index')] = i
    if i == 10:
        i = 0
    else:
        i += 1
        j += 1
df_raw['index'].unique()
df_raw

,Uncertainty Measure,Uncertainty Type,Dataset,PRR (MCR),PRR (MAE),PRR (MSE),index
index,,,,,,,
6,ord-ent,TU,Abalone,0.196734,0.288851,0.319262,0
7,ord-ent,EU,Abalone,0.170817,0.242937,0.267086,1
8,ord-ent,AU,Abalone,0.199899,0.290685,0.318964,2
24,ord-ent,TU,Abalone,0.209714,0.304864,0.442227,3
25,ord-ent,EU,Abalone,0.211950,0.309945,0.453589,4
...,...,...,...,...,...,...,...
154,var,EU,Wisconsin Breast Cancer,-0.313830,0.050868,0.019804,5
155,var,AU,Wisconsin Breast Cancer,-0.169453,-0.088029,-0.024463,6
171,var,TU,Wisconsin Breast Cancer,0.177052,0.489815,0.612026,7
172,var,EU,Wisconsin Breast Cancer,-0.313830,-0.208025,-0.155894,8
173,var,AU,Wisconsin Breast Cancer,0.177052,0.489815,0.612026,9

In [26]:
import pandas as pd

df_raw = df_raw.copy()

MAXIMIZE_OUTCOME = True

In [27]:
df = pd.DataFrame()

for m in METRICS:
    df_next = df_raw.pivot(
        index=['index', "Dataset", 'Uncertainty Type'],
        columns="Uncertainty Measure",
        values=m
    )

    df = pd.concat([df, df_next])

df

Uncertainty Measure                              bin-ent   bin-var       ent  \
index Dataset                 Uncertainty Type
0     Abalone                 AU                0.302324  0.324566  0.335736
                              EU               -0.254294 -0.252172 -0.197375
                              TU                0.278425  0.285761  0.292519
      Auto MPG                AU                0.243948  0.223515  0.207168
                              EU                0.426623  0.410004  0.414159
...                                                  ...       ...       ...
9     Obesity                 EU                0.807763  0.807763  0.811646
                              TU                0.980676  0.983091  0.983091
      Wisconsin Breast Cancer AU                0.583642  0.536728  0.513272
                              EU                0.062003  0.182031  0.119794
                              TU                0.410995  0.450262  0.450262

Uncertainty Measure                              ord-ent   ord-var       var
index Dataset                 Uncertainty Type
0     Abalone                 AU                0.342299  0.334443  0.340509
                              EU               -0.200541 -0.203953 -0.193556
                              TU                0.288851  0.273569  0.283214
      Auto MPG                AU                0.231688  0.235775  0.272556
                              EU                0.468172  0.497257  0.484792
...                                                  ...       ...       ...
9     Obesity                 EU                0.827180  0.825239  0.821355
                              TU                0.987922  0.987922  0.987922
      Wisconsin Breast Cancer AU                0.489815  0.478086  0.489815
                              EU                0.133131 -0.053580 -0.169162
                              TU                0.476440  0.463351  0.391361

[480 rows x 6 columns]

In [28]:
from critdd import Diagram

# create a CD diagram from the Pandas DataFrame
diagram = Diagram(
    df.to_numpy(),
    treatment_names=df.columns,
    maximize_outcome=MAXIMIZE_OUTCOME
)

# inspect average ranks and groups of statistically indistinguishable treatments
diagram.average_ranks  # the average rank of each treatment
diagram.get_groups(alpha=.05, adjustment="holm")

# export the diagram to a file
diagram.to_file(
    "cd_result.tex",
    alpha=.05,
    adjustment="holm",
    reverse_x=False,
    axis_options={"title": UNCERTAINTY_TYPE + ' - ' + ', '.join(METRICS)
                  },
)