In [13]:
import pandas as pd
import seaborn as sns

TYPE = 'TU'
DATA = 'left_tail'
PRR = "PRR (MAE)"
GROUP = 'tail'

prrs = pd.read_csv(f'prrs_{DATA}.csv')

# Rename uncertainty measures
prrs = prrs.replace(f'Entropy', "ent")
prrs = prrs.replace(f'Variance', "var")
prrs = prrs.replace(f"Binary Entropy", "ord-ent")
prrs = prrs.replace(f"Binary Variance", "ord-var")
prrs = prrs.replace(f"Binary Entropy One vs. Rest", "bin-ent")
prrs = prrs.replace(f"Binary Variance One vs. Rest", "bin-var")

prrs

,Uncertainty Measure,Uncertainty Type,PRR (MCR),PRR (MAE),PRR (MSE),Group
0,ent,TU,0.173506,0.066847,0.008978,tail
1,ent,EU,0.104162,0.042883,0.042598,tail
2,ent,AU,0.167878,0.061134,0.002464,tail
3,ord-var,TU,0.209685,0.100015,0.024101,tail
4,ord-var,EU,0.167476,0.083987,0.052021,tail
...,...,...,...,...,...,...
535,bin-var,EU,0.953238,0.960635,0.966862,head
536,bin-var,AU,0.981760,0.987129,0.993034,head
537,bin-ent,TU,0.981271,0.987236,0.992935,head
538,bin-ent,EU,0.967315,0.973185,0.979301,head
539,bin-ent,AU,0.982740,0.988201,0.993432,head

In [14]:
prrs = prrs[(prrs["Uncertainty Type"] == TYPE) & (prrs["Group"] == GROUP)]
prrs

,Uncertainty Measure,Uncertainty Type,PRR (MCR),PRR (MAE),PRR (MSE),Group
0,ent,TU,0.173506,0.066847,0.008978,tail
3,ord-var,TU,0.209685,0.100015,0.024101,tail
6,ord-ent,TU,0.196620,0.093509,0.021658,tail
9,var,TU,0.217926,0.114616,0.039806,tail
12,bin-var,TU,0.179335,0.065101,0.003394,tail
15,bin-ent,TU,0.177727,0.055262,-0.005098,tail
54,ent,TU,0.087731,0.061251,0.027918,tail
57,ord-var,TU,0.122114,0.095874,0.056565,tail
60,ord-ent,TU,0.096073,0.070175,0.042447,tail
63,var,TU,0.112552,0.090520,0.064789,tail
66,bin-var,TU,0.106652,0.076243,0.032167,tail
69,bin-ent,TU,0.127404,0.093019,0.036142,tail
108,ent,TU,0.087789,0.110022,0.177031,tail
111,ord-var,TU,0.107598,0.126917,0.196485,tail
114,ord-ent,TU,0.094992,0.118635,0.182785,tail
117,var,TU,0.105597,0.125095,0.185388,tail
120,bin-var,TU,0.095192,0.115322,0.185251,tail
123,bin-ent,TU,0.105997,0.120623,0.192649,tail
162,ent,TU,0.076474,-0.002398,-0.034295,tail
165,ord-var,TU,0.104009,0.027517,-0.009230,tail
168,ord-ent,TU,0.083763,0.002820,-0.037713,tail
171,var,TU,0.104616,0.022647,-0.019484,tail
174,bin-var,TU,0.087609,0.010647,-0.021335,tail
177,bin-ent,TU,0.105628,0.030995,-0.005100,tail
216,ent,TU,0.192042,0.102527,-0.056795,tail
219,ord-var,TU,0.236264,0.146766,-0.033021,tail
222,ord-ent,TU,0.231395,0.136720,-0.052194,tail
225,var,TU,0.257563,0.166154,-0.024125,tail
228,bin-var,TU,0.196302,0.110106,-0.039617,tail
231,bin-ent,TU,0.196099,0.111692,-0.025812,tail
270,ent,TU,0.149985,0.005884,-0.030697,tail
273,ord-var,TU,0.172853,0.024960,-0.007586,tail
276,ord-ent,TU,0.163109,0.022898,-0.002148,tail
279,var,TU,0.188066,0.056840,0.046862,tail
282,bin-var,TU,0.158039,0.006657,-0.037970,tail
285,bin-ent,TU,0.165197,0.008891,-0.042321,tail
324,ent,TU,0.137069,0.049441,0.051627,tail
327,ord-var,TU,0.181547,0.085924,0.073001,tail
330,ord-ent,TU,0.176162,0.085051,0.075213,tail
333,var,TU,0.214457,0.121708,0.103663,tail
336,bin-var,TU,0.139463,0.047521,0.049121,tail
339,bin-ent,TU,0.143851,0.044379,0.040276,tail
378,ent,TU,0.153032,0.078219,-0.009389,tail
381,ord-var,TU,0.182398,0.107356,0.012362,tail
384,ord-ent,TU,0.173667,0.097967,0.002831,tail
387,var,TU,0.192915,0.119820,0.026048,tail
390,bin-var,TU,0.157794,0.083884,-0.001202,tail
393,bin-ent,TU,0.163151,0.092140,0.011018,tail
432,ent,TU,0.183679,0.189679,0.169589,tail
435,ord-var,TU,0.208456,0.230731,0.206922,tail
438,ord-ent,TU,0.204060,0.221923,0.201011,tail
441,var,TU,0.217847,0.240870,0.213610,tail
444,bin-var,TU,0.182481,0.189513,0.168656,tail
447,bin-ent,TU,0.172290,0.178544,0.153567,tail
486,ent,TU,0.094231,0.082268,-0.048594,tail
489,ord-var,TU,0.115622,0.105558,-0.043663,tail
492,ord-ent,TU,0.109086,0.100772,-0.035571,tail
495,var,TU,0.125129,0.119117,-0.018627,tail
498,bin-var,TU,0.095023,0.080513,-0.059721,tail
501,bin-ent,TU,0.097004,0.077322,-0.074389,tail

In [15]:
prrs['rank'] = prrs['PRR (MAE)'].rank(ascending=False)

prrs = prrs.groupby(["Group","Uncertainty Type","Uncertainty Measure" ]).agg(
            ['mean'])[('rank','mean')].rank().sort_values()

#  # Export as a Booktabs LaTeX table
# latex_str = prrs.to_latex(
#     index=True
# )
#
# # Save to file
# with open("./test.tex", 'w') as f:
#     f.write(latex_str)
prrs

C:\Users\Q454199\AppData\Local\Temp\ipykernel_8296\422899808.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prrs['rank'] = prrs['PRR (MAE)'].rank(ascending=False)

Group  Uncertainty Type  Uncertainty Measure
tail   TU                var                    1.0
                         ord-var                2.0
                         ord-ent                3.0
                         bin-ent                4.0
                         bin-var                5.0
                         ent                    6.0
Name: (rank, mean), dtype: float64

In [16]:
from matplotlib import pyplot as plt



sns.set_theme(context='paper', style='whitegrid', font_scale=2.2, font="serif", rc={
    "text.usetex": True
})

ax = sns.boxplot(data=prrs, showfliers=False, x="Uncertainty Measure", y=PRR, hue="Uncertainty Measure")
ax.set(xlabel=None)

plt.savefig(TYPE + "_"+ DATA + "_"+GROUP+"_"+PRR+".pdf", bbox_inches='tight', dpi=300)

plt.show()

TypeError: Data source must be a DataFrame or Mapping, not <class 'pandas.core.series.Series'>.